name:                mazes
version:             0.1.0.0
github:              "Berengal/mazes"
license:             BSD3
author:              "Sjur Gjøstein Karevoll"
maintainer:          "sjurberengal@gmail.com"
copyright:           "2019 Sjur Gjøstein Karevoll"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Berengal/mazes#readme>

dependencies:
- base >= 4.7 && < 5
- vector >= 0.12.0.2 && < 0.13
- MonadRandom >= 0.5.1.1 && < 0.6
- random >= 1.1 && < 2
- array >= 0.5.3.0 && < 0.6
- containers >= 0.6.0.1 && < 0.7
- text >= 1.2.3.1 && < 1.3
- JuicyPixels >= 3.3.3 && < 3.4

library:
  source-dirs: src

executables:
  mazes-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mazes

tests:
  mazes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mazes
    - QuickCheck >= 2.12.6.1 && < 3
    - hspec >= 2.6.1 && < 3
